apiVersion: v1
kind: Service
metadata:
  name: cdk8s-app-hello-service-c80456b4
spec:
  ports:
    - nodePort: 30080
      port: 8000
      targetPort: 8000
  selector:
    app: cdk8sapphello8162FB24
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8s-app-hello-deployment-c855f592
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cdk8sapphello8162FB24
  template:
    metadata:
      labels:
        app: cdk8sapphello8162FB24
    spec:
      containers:
        - image: paulbouwer/hello-kubernetes:1.7
          name: app
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: cdk8s-app-pgadmin4-service-c8283e0f
spec:
  ports:
    - nodePort: 30080
      port: 8080
      targetPort: 80
  selector:
    app: cdk8sapppgadmin474D32443
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdk8s-app-pgadmin4-deployment-c838fa72
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdk8sapppgadmin474D32443
  template:
    metadata:
      labels:
        app: cdk8sapppgadmin474D32443
    spec:
      containers:
        - env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: me@mail.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: absecret123
          image: dpage/pgadmin4
          name: app
          ports:
            - containerPort: 80
